### ISSUE TITLE
trac-wikinotification on trac 0.12 AttributeError: 'Environment' object has no attribute 'db_query'

### ISSUE THREAD

**Issue by younis84** [trac-hacks/trac-wikinotification#8]
Attached
![wikinotification_error_page1](https://cloud.githubusercontent.com/assets/15221091/10621366/65bbd0f2-774e-11e5-99fa-9ba1555faa9d.png)
![wiki_notification_error_page2](https://cloud.githubusercontent.com/assets/15221091/10621369/6a4a8c8a-774e-11e5-8e26-d99197f1e56a.png)

**Comment by mitar** [comment]
Are you using git repository version or PyPi version? PyPi should work on 0.12. `master` should not anymore.

**Comment by mitar** [comment]
Please check. I can reopen the ticket if does not work with 0.3 for you.

**Comment by snelgar** [comment]
Helping Younis here. We were using 0.3, as per the line item in the trace for "Enabled Plugins". Going to PyPi we found it was offering 0.4. You're saying to try 0.3, so that doesn't sound right; but just in case of a typo we tried the 0.4. That doesn't work at all -- the 0.3 version offered us "Watch this page" in the appropriate spot but died on page update; 0.4 doesn't seem to do anything.

**Comment by snelgar** [comment]
Oops, finger trouble; restarted the wrong trac instance. We now get the "Watch Page" piece working, with 0.4 (as well as with the 0.3 we had before), but still have the same "db_query" crash on page update.

**Comment by younis84** [comment]
Thanks Mitar, I am still getting same error for PyPi version 0.4


![error_0 4_pypi](https://cloud.githubusercontent.com/assets/15221091/10643885/4db47bda-77f3-11e5-89cd-a5d77bd56126.png)

**Comment by mitar** [comment]
The 0.4 version removed `db_query`, see this commit: ce6377e5c125fdd2fac91cb13097c08e80888bac

The version before (0.3) should still have it and should work.

Feel free to make a pull request which makes code work both on new and old version. Probably you can simply check for existence of `db_query` and if there is none, you go the old way.

**Comment by snelgar** [comment]
Ah; I think we are confused about versions. Creating an egg from the master with "python26 setup.py bdist_egg" produces an egg called "TracWikiNotification-0.3-py2.6.egg" -- which we had been figuring must be version 0.3, due to the name. But it comes from the GitHub Master, which is presumably more recent.
The PyPi distribution is 0.4, and uses db_query (as does master: both contain the line in question:
WikiNotification/notification.py:        with self.env.db_query as db:

I'm too new to GitHub to get the pull request for a 0.12-compatible version right; can you advise?

**Comment by mitar** [comment]
No, `master` should not (since yesterday) produce 0.4 and is the same as 0.4. 0.3 version is older version.

Have you tried using 0.3 version from PyPi?

**Comment by snelgar** [comment]
All I find in PyPi is 0.4.
I note that you're referring in the commit: ce6377e to admin.py, but our problem is in notification.py
Can you point us to a URL that gets the right thing?

**Comment by mitar** [comment]
PyPi has also older versions? https://pypi.python.org/pypi/TracWikiNotification/0.3

```
pip install TracWikiNotification@0.3
```

Probably.

**Comment by mitar** [comment]
Or maybe it was `0.2.3` the latest version to support 0.12. Try that one.

**Comment by snelgar** [comment]
0.3 gives a big crash: no pages render at all. There's a text dump as follows

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Trac-0.12-py2.6.egg/trac/web/api.py", line 436, in send_error
    data, 'text/html')
  File "/usr/lib/python2.6/site-packages/Trac-0.12-py2.6.egg/trac/web/chrome.py", line 808, in render_template
    template = self.load_template(filename, method=method)
  File "/usr/lib/python2.6/site-packages/Trac-0.12-py2.6.egg/trac/web/chrome.py", line 769, in load_template
    self.get_all_templates_dirs(), auto_reload=self.auto_reload,
  File "/usr/lib/python2.6/site-packages/Trac-0.12-py2.6.egg/trac/web/chrome.py", line 482, in get_all_templates_dirs
    dirs.extend(provider.get_templates_dirs() or [])
  File "build/bdist.linux-x86_64/egg/WikiNotification/web_ui.py", line 39, in get_templates_dirs
    resource_dir = resource_filename(__name__, 'templates')
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1161, in resource_filename
    self, resource_name
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1862, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1883, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'WikiNotification/templates'

**Comment by snelgar** [comment]
And I don't know how to get 0.2.3.

**Comment by snelgar** [comment]
For whatever reason, the "templates" directory was not in the https://pypi.python.org/pypi/TracWikiNotification/0.3 distro, so I added it back in (stolen form 0.4).
The notification.py problem (using db_query at line 161) is still in this (0.3 from PyPi) rev, so I replaced it with the version at https://github.com/trac-hacks/trac-wikinotification/commit/5ed1d9dd0544f5cf2e8152b4cac18d81a3c2324c 
and now it seems to work
